### ISSUE TITLE
meauthz v1 is no longer available

### ISSUE THREAD

**Issue by MarkBracke** [digipolisantwerp/auth_module_nodejs#54]
Situation:

meauthz v1 is hardcoded in /lib/service.js. 
This makes it almost impossible for new application to use fetchPermissions=true as meauthz v1 is no longer available for new applications. Access to meauthz v1 can probably still be requested by contacting the right persons.

To fix, replace the url:

`${config.apiHost}/acpaas/meauthz/v1/applications/${config.applicationName}/permissions`

with:

`${config.apiHost}/acpaas/meauthz/v2/permissions?applicationId=${config.applicationName}`

**Comment by Jan-Bart** [comment]
Should be fixed in 1.6.1
